frr version 8.4
frr defaults traditional
hostname r2
log stdout
!
interface eth1
 ip address 10.0.12.2/30
!
interface eth2
 ip address 10.0.23.1/30
!
router ospf
 network 10.0.12.0/30 area 0
 network 10.0.23.0/30 area 0
!
line vty
